version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:401032571731:task-definition/todo-rest-application-task:1"
        LoadBalancerInfo:
          ContainerName: "todo-rest-application-container"
          ContainerPort: "8080"
        PlatformVersion: "LATEST"